### ISSUE TITLE
Stacks Node not updated to version 3

### ISSUE THREAD

**Issue by HariSeldon23** [hirosystems/charts#32]
We are using the Helm charts from Hiro for our Stacks node and currently the latest version on the Helm chart is still 2.5.

Now that Nakamoto is live we are looking at running v3. We use our Node extensively to power our indexing solution and now with fast blocks we need to run our own node to ensure we have minimal latency.

Do you have a timeframe for updating the Helm chart to Stacks client 3? Is there any way I could help to hasten the delivery?

Appreciate it!

**Comment by CharlieC3** [comment]
This has been updated in a recent release! Also Helm chart releases may lag behind releases from the Stacks Core repo. Feel free to override the tag value (or any other value) as needed.

**Comment by HariSeldon23** [comment]
Thanks @CharlieC3 you're a scholar and a gentleman!
